# Machine Learning and Data Analysis
----------------------------------------------
### *Session 5.2*


```
20th October, 2023
Anna Pallarès López
Computer Engineering Master's

```

# Import, adapt and visualize data

In [3]:
from sklearn.datasets import fetch_openml

In [ ]:
mnist = fetch_openml('mnist_784')

In [4]:
X = mnist.data
Y = mnist.target

In [8]:
X = X.to_numpy()
Y = Y.to_numpy()

In [13]:
# we need to transfor this array of carachters to array of numbers
import numpy as np
Y = np.asarray([eval(i) for i in Y])

In [20]:
# negative and positive digits
dn = 0
dp = 1
mask = (Y == dn) | (Y == dp)
X = X[mask, :]
Y = Y[mask]
# the order of assigning first the negative and after the positive is important
# if we don't do i like this, all digits can be assigned to a wrong one
Y[Y == dn] = -1
Y[Y == dp] = +1


In [24]:
from random import sample

n = 100
nt = 1000
mask = np.asarray(sample(range(X.shape[0]),n+nt))

X = X[mask,:]
Y = Y[mask]
mask = range(n,n+nt)

Xt = X[mask,]
Yt = Y[mask]
mask = range(0,n)

X = X[mask,]
Y = Y[mask]

print(X.shape)
print(Y.shape)
print(Xt.shape)
print(Yt.shape)

(100, 784)
(100,)
(1000, 784)
(1000,)


In [29]:
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

grid = {'alpha'  : np.logspace(-4,3,30)}

MS = GridSearchCV(estimator   = RidgeClassifier(),
                  param_grid  = grid,
                  scoring     = 'accuracy',
                  cv          = 10)

H = MS.fit(X,Y)
M = RidgeClassifier(alpha= H.best_params_['alpha'])
M.fit(X,Y)
Yp = M.predict(Xt)

print(np.mean(Yp * Yt <= 0))
print(confusion_matrix(Yt,Yp))

0.003
[[472   2]
 [  1 525]]


In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

grid = {'penalty' : ['l1'],
        'C'       : np.logspace(-4,3,30),
        'solver'  : ['liblinear']}

MS = GridSearchCV(estimator   = LogisticRegression(),
                  param_grid  = grid,
                  scoring     = 'accuracy',
                  cv          = 10)

H = MS.fit(X,Y)
M = LogisticRegression(penalty = H.best_params_['penalty'],
                       C       = H.best_params_['C'],
                       solver  = H.best_params_['solver'])
M.fit(X,Y)
Yp = M.predict(Xt)

print(np.mean(Yp * Yt <= 0))
print(confusion_matrix(Yt,Yp))

0.005
[[471   3]
 [  2 524]]


In [ ]:
print(M.coef_)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
grid = {'penalty' : ['l1','l2'],
        'C'       : np.logspace(-4,3,30),
        'solver'  : ['liblinear']}
MS = GridSearchCV(estimator   = LogisticRegression(),
                  param_grid  = grid,
                  scoring     = 'accuracy',
                  cv          = 10)
H = MS.fit(X,Y)
M = LogisticRegression(penalty = H.best_params_['penalty'],
                       C       = H.best_params_['C'],
                       solver  = H.best_params_['solver'])
M.fit(X,Y)
Yp = M.predict(Xt)
print(np.mean(Yp * Yt <= 0))
print(confusion_matrix(Yt,Yp))

0.003
[[471   3]
 [  0 526]]


In [38]:
H.best_params_['penalty']

'l2'

In [ ]:
# in this case sparsity is a good property as we only need few pixels to know
# if the image is a 0 or a 1