# Machine Learning and Data Analysis
----------------------------------------------
### *Session 5.3*


```
20th October, 2023
Anna Pallarès López
Computer Engineering Master's

```

# Import, adapt and visualize data

In [1]:
from sklearn.datasets import fetch_openml

In [2]:
mnist = fetch_openml('mnist_784')

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
X = mnist.data
Y = mnist.target

In [4]:
X = X.to_numpy()
Y = Y.to_numpy()

In [5]:
# we need to normalize the data

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [6]:
# we need to transfor this array of carachters to array of numbers

import numpy as np

Y = np.asarray([eval(i) for i in Y])

In [7]:
from random import sample

n = 3000
nt = 10000
mask = np.asarray(sample(range(X.shape[0]),n+nt))

X = X[mask,:]
Y = Y[mask]
mask = range(n,n+nt)

Xt = X[mask,]
Yt = Y[mask]
mask = range(0,n)

X = X[mask,]
Y = Y[mask]

In [8]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

M = SVC(C      = 1,
        kernel = 'linear')

M.fit(X,Y)
Yp = M.predict(Xt)

print(np.mean(Yp != Yt))
print(confusion_matrix(Yt,Yp))


0.0959
[[ 940    0    9    2    2    8    6    0    1    0]
 [   0 1099    5    2    2    2    0    5    9    1]
 [   8   15  879   17   12    5   10   19   13    7]
 [   3    7   22  902    0   40    4    9   10    4]
 [   7    3   12    2  885    0    6   14    2   43]
 [  15   10   12   47   10  781   14    0   13   13]
 [  11    2   17    0    8   23  937    0    3    0]
 [   8   13   16    8   13    2    0  979    1   44]
 [   5   26   23   47    6   32    5   11  758   13]
 [   8    7    3   21   44    7    1   46    3  881]]


In [10]:
from sklearn.model_selection import GridSearchCV

# if we optimize the hyperparameter, we get even a best result
grid = {'C'      : np.logspace(-4,3,10),
        'kernel' : ['linear']}

MS = GridSearchCV(estimator   = SVC(),
                  param_grid  = grid,
                  scoring     = 'accuracy',
                  cv          = 10,
                  verbose     = 2)

H = MS.fit(X,Y)

M = SVC(C      = H.best_params_['C'],
        kernel = H.best_params_['kernel'])

M.fit(X,Y)
Yp = M.predict(Xt)

print(np.mean(Yp * Yt <= 0))
print(confusion_matrix(Yt,Yp))

Fitting 10 folds for each of 10 candidates, totalling 100 fits
[CV] END ............................C=0.0001, kernel=linear; total time=   2.4s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.3s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.3s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.4s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END ............................C=0.0001, kernel=linear; total time=   2.2s
[CV] END .............C=0.0005994842503189409, kernel=linear; total time=   1.6s
[CV] END .............C=0.0005994842503189409,

In [ ]:
from sklearn.model_selection import GridSearchCV

# if moreover we optimize the parameter alpha, computational time increases but the model should be even better
grid = {'C'      : np.logspace(-4,3,10),
        'kernel' : ['rbf'],
        'gamma'  : np.logspace(-4,3,10)}

MS = GridSearchCV(estimator   = SVC(),
                  param_grid  = grid,
                  scoring     = 'accuracy',
                  cv          = 10,
                  verbose     = 2)

H = MS.fit(X,Y)

M = SVC(C      = H.best_params_['C'],
        kernel = H.best_params_['kernel'],
        gamma  = H.best_params_['gamma'])

M.fit(X,Y)
Yp = M.predict(Xt)

print(np.mean(Yp * Yt <= 0))
print(confusion_matrix(Yt,Yp))

0.005
[[471   3]
 [  2 524]]


In [ ]:
# if we still don't even improve the accuracy on the model,
# will be due to the small amount of data